apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{BOT-NAME}}
  name: {{BOT-NAME}}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: {{BOT-NAME}}
  template:
    metadata:
      labels:
        component: {{BOT-NAME}}
    spec:
      containers:
      - args:
        - --{{PLATFORM}}-token-path=/app/conf/robot-{{PLATFORM}}/robot_token
        - --plugin-config=/app/conf/robot-{{PLATFORM}}/app_config.yaml
        image: {{IMAGE}}
        imagePullPolicy: IfNotPresent
        name: {{BOT-NAME}}
        ports:
        - containerPort: {{PORT}}
          name: http
          protocol: TCP
        volumeMounts:
        - mountPath: /app/conf/robot-{{PLATFORM}}/robot_token
          subPath: robot-token
          name: secret-volume
        - mountPath: app/conf/robot-{{PLATFORM}}/app_config.yaml
          subPath: config.yaml
          name: app-config
          readOnly: true
      volumes:
      - name: secret-volume
        secret:
          secretName: robot-{{PLATFORM}}-secrets
      - name: app-config
        configMap:
          name: robot-{{PLATFORM}}-{{BOT-NAME}}
