apiVersion: v1
kind: Service
metadata:
  name: {{BOT-NAME}}
spec:
  ports:
  - name: httpport
    port: {{PORT}}
    protocol: TCP
    targetPort: {{PORT}}
  selector:
    component: {{BOT-NAME}}
  type: ClusterIP
